# Generated by Django 4.1.5 on 2023-03-02 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicStory',
            fields=[
                ('id_cs', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('name_doctor', models.CharField(max_length=100)),
                ('archive', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('patient_number', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('birthday', models.DateTimeField()),
                ('precautions', models.CharField(max_length=300)),
                ('date_adminission', models.DateTimeField()),
                ('proccedings', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ViaChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('num_order', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('1', 'Plan de cuidados'), ('2', 'Tarjeta Médica')], max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('atettions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_cs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_app.clinicstory')),
                ('ine_nurs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.nursuser')),
            ],
        ),
        migrations.CreateModel(
            name='Interment',
            fields=[
                ('num_interment', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('date_admision', models.DateField()),
                ('egress_date', models.DateField(blank=True, null=True)),
                ('living_room', models.CharField(max_length=20)),
                ('bed_number', models.CharField(max_length=5)),
                ('condition', models.CharField(max_length=10)),
                ('diagnosis', models.CharField(max_length=20)),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('control_number', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('pressure', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('oxygen', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pulse', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weigth', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patientuser')),
            ],
        ),
        migrations.AddField(
            model_name='clinicstory',
            name='patient_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_app.patientuser'),
        ),
    ]
