# Generated by Django 4.1.5 on 2023-03-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id_workstation', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('ine_nurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.nursuser')),
                ('ine_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse_WorkStation',
            fields=[
                ('id_nurs_workstation', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('id_workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_app.workstation')),
                ('ine_nurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.nursuser')),
            ],
        ),
        migrations.CreateModel(
            name='InputRequest',
            fields=[
                ('application_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('note', models.CharField(max_length=300)),
                ('ine_nurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.nursuser')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionOrder',
            fields=[
                ('num_attention', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('attention_time', models.DateTimeField()),
                ('completed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('num_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_app.medicalorder')),
            ],
        ),
    ]
