# Generated by Django 4.1.5 on 2023-03-02 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id_shift', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('entry_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('number_nurses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
